---
title: "analysis"
output: html_document
date: "2024-08-08"
---

# Code used for the analysis and graphs

## 1. Regressions

General form of the regression: 
judgment ~ group_type*question_type + (1|participant)

### 1. A. Group 1 (full training) vs. Group 2 (partial training)
```{r}
library(lmerTest)

# Load the data from CSV
data <- read.csv('data/filtered_data.csv')

# filter Groups 1 and 2
data <- subset(data, Group %in% c(1, 2))

# convert factors to numeric codes
# Group 1 is full training, Group 2 is partial training
data$group_type <- ifelse(data$Group == 1, -0.5, 0.5) 
# Validation questions coded as -0.5, joint inference as 0.5 (per pre-registration document)
data$question_type <- ifelse(data$is_val == 1, -0.5, 0.5)  

# Run the linear mixed-effects regression
model <- lmer(Test_Score ~ group_type * question_type + (1|Participant_id), data=data)

# Output the summary of the model
summary(model)
```


### 1. B. Group 2 (partial training) vs. Group 3 (no training)
```{r}
library(lmerTest)

# Load the data from CSV
data <- read.csv('data/filtered_data.csv')

# Filter out the data for Groups 2 and 3 only
data <- subset(data, Group %in% c(2, 3))

# Convert group type and question type to effect coding
# Group 2 is partial training, Group 3 is no training
data$group_type <- ifelse(data$Group == 2, -0.5, 0.5)  
# Code validation questions as -0.5, joint inference as 0.5
data$question_type <- ifelse(data$is_val == 1, -0.5, 0.5)  

# Run the linear mixed-effects regression using lmer
model <- lmer(Test_Score ~ group_type * question_type + (1|Participant_id), data=data)

# Output the summary of the model
summary(model)
```
